---

  - name: 2.3.1 Ensure NIS Client is not installed (Scored)
    apt:
      name: nis
      state: absent
    tags:
      - level1
      - section02
      - section02.03
      - section02.03.01

  - name: 2.3.2 Ensure rsh client is not installed (Scored)
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - rsh-client
      - rsh-redone-client
    tags:
      - level1
      - section02
      - section02.03
      - section02.03.02

  - name: 2.3.3 Ensure talk client is not installed (Scored)
    apt:
      name: talk
      state: absent
    tags:
      - level1
      - section02
      - section02.03
      - section02.03.03

  - name: 2.3.4 Ensure telnet client is not installed (Scored)
    apt:
      name: telnet
      state: absent
    tags:
      - level1
      - section02
      - section02.03
      - section02.03.04

  - name: 2.3.5 Ensure LDAP client is not installed (Scored)
    apt:
      name: ldap-utils
      state: absent
    tags:
      - level1
      - section02
      - section02.03
      - section02.03.05
