---

  - name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
    apt:
      name: "{{ntp_package}}"
      state: present
    tags:
      - level1
      - section02
      - section02.02
      - section02.02.01.01

  - name: 2.2.1.2 Ensure ntp is configured (Scored)
    lineinfile:
      dest: "{{ item.name }}"
      regexp: '{{item.expression}}'
      line: '{{item.value}}'
    with_items:
      - { name: '/etc/ntp.conf' , expression: '^server' , value: 'pool 10.190.14.12' }
      - { name: '/etc/ntp.conf' , expression: '^restrict -4' , value: 'restrict -4 default kod nomodify notrap nopeer noquery' }
      - { name: '/etc/ntp.conf' , expression: '^restrict -6' , value: 'restrict -6 default kod nomodify notrap nopeer noquery' }
      - { name: '/etc/init.d/ntp', expression: '^RUNASUSER' , value: 'RUNASUSER=ntp' }
    when: ntp_package  == "ntp"
    notify: restart ntp
    tags:
      - level1
      - section02
      - section02.02
      - section02.02.01.02

  - name: 2.2.1.3 Ensure chrony is configured (Scored)
    lineinfile:
      dest: "{{ item.name }}"
      regexp: '{{item.expression}}'
      line: '{{item.value}}'
    with_items:
      - { name: '/etc/chrony/chrony.conf', expression: '^server', value: 'server 10.190.14.12' }
      - { name: '/etc/chrony/chrony.conf', expression: '^pool', value: '' }
    when: ntp_package  == "chrony"
    notify: restart chrony
    tags:
      - level1
      - section02
      - section02.02
      - section02.02.01.03

  - name: 2.2.2 Ensure X Window System is not installed (Scored)
    apt:
      name: xserver-xorg-core*
      purge: yes
      state: absent
    when: remove_xserver == True
    tags:
      - level1
      - section02
      - section02.02
      - section02.02.02

  - name: 2.2.3 Ensure Avahi Server is not enabled (Scored)
    command: dpkg-query -s avahi-daemon
    register: avahi_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.03

  - service:
      name: avahi-daemon
      state: stopped
      enabled: no
    when: avahi_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.03


  - name: 2.2.3 Ensure Avahi Server is not enabled (check) (Scored)
    stat: path='/etc/init/avahi-daemon.conf'
    register: avahi_stat
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.03

  - lineinfile: >
        line='#start on (filesystem'
        state=present
        regexp='start on \(filesystem'
        dest=/etc/init/avahi-daemon.conf
    when: avahi_stat.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.03

  - name: 2.2.4 Ensure CUPS is not enabled (Scored)
    command: dpkg-query -s cups-server-common
    register: cups_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.04

  - service:
      name: cups
      state: stopped
      enabled: no
    when: cups_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.04



  - name: 2.2.4 Ensure CUPS is not enabled (Scored)
    stat: path='/etc/init/cups.conf'
    register: cups_stat
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.04

  - lineinfile: >
        line='#start on (filesystem'
        state=present
        regexp='start on \(filesystem'
        dest=/etc/init/cups.conf
    when: cups_stat.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.04



  - name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
    command: dpkg-query -s isc-dhcp-server
    register: dhcp_installed
    failed_when: False 
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.05

  - command: dpkg-query -s isc-dhcp-server6
    register: dhcp6_installed
    failed_when: False 
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.05

  - service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - isc-dhcp-server
      - isc-dhcp-server6
    when: dhcp_installed.rc == 0 or dhcp6_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.05

  - name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
    stat: path='/etc/init/isc-dhcp-server.conf'
    register: dhcp_stat
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.05

  - lineinfile: >
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
        dest=/etc/init/isc-dhcp-server.conf
    when: dhcp_stat.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.05

  - stat: path='/etc/init/isc-dhcp-server6.conf'
    register: dhcp6_stat
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.05

  - lineinfile: >
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
        dest=/etc/init/isc-dhcp-server6.conf
    when: dhcp6_stat.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.05

  - name: 2.2.6 Ensure LDAP server is not enabled (Scored)
    command: dpkg-query -s slapd
    register: ldap_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.06

  - service:
      name: slapd
      state: stopped
      enabled: no
    when: ldap_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.06

  - name: 2.2.6 Ensure LDAP server is not enabled (Scored)
    apt: name=slapd purge=yes state=absent
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.06





  - name: 2.2.7 Ensure NFS and RPC are not enabled (Scored)
    command: dpkg-query -s nfs-kernel-server
    register: nfs_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.07

  - command: dpkg-query -s rpcbind
    register: rpcbind_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.07

  - service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - rpcbind
      - nfs-server
    when: rpcbind_installed.rc == 0 or nfs_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.07


  - name: 2.2.7 Ensure NFS and RPC are not enabled (Scored)
    stat: path=/etc/init/rpcbind-boot.conf
    register: nfs_rpc_rc
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.07

  - lineinfile: >
        dest=/etc/init/rpcbind-boot.conf
        line='#start on virtual-filesystems and net-device-up IFACE=lo'
        state=present
        regexp='start on virtual-filesystems and net'
    when: nfs_rpc_rc.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.07

  - command: dpkg -S nfs-kernel-server
    changed_when: False
    failed_when: False
    always_run: True
    register: nfs_present
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.07

  - service: >
        name=nfs-kernel-server
        enabled=no
    when: nfs_present is defined and nfs_present.rc == 0
    register: nfs_service_result
    failed_when: "nfs_service_result|failed and 'service not found' not in nfs_service_result.msg"
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.07


  - name: 2.2.8 Ensure DNS Server is not enabled (Scored)
    command: dpkg-query -s bind9
    register: bind9_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.08

  - service:
      name: bind9
      state: stopped
      enabled: no
    when: bind9_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.08



  - name: 2.2.9 Ensure FTP Server is not enabled (Scored)
    command: dpkg-query -s vsftpd
    register: vsftpd_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.09

  - service:
      name: vsftpd
      state: stopped
      enabled: no
    when: vsftpd_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.09

  - name: 2.2.10 Ensure HTTP server is not enabled (Scored)
    command: dpkg-query -s apache2
    register: apache2_installed
    failed_when: False 
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.10

  - service:
      name: apache2
      state: stopped
      enabled: no
    when: apache2_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.10

  - name: 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
    command: dpkg-query -s dovecot
    register: dovecot_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.11

  - command: dpkg-query -s exim
    register: exim_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.11

  - command: dpkg-query -s cyrus-imap
    register: cyrus_imap_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.11

  - service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - dovecot
      - exim
      - cyrus-imap
    when: dovecot_installed.rc == 0 or exim_installed.rc == 0 or cyrus_imap_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.11

  - name: 2.2.12 Ensure Samba is not enabled (Scored)
    command: dpkg-query -s smbd
    register: smbd_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.12

  - service:
      name: smbd
      state: stopped
      enabled: no
    when: smbd_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.12

  

  - name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
    command: dpkg-query -s squid
    register: squid_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.13

  - service:
      name: squid
      state: stopped
      enabled: no
    when: squid_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.13

  - name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
    command: dpkg-query -s snmpd
    register: snmpd_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.14

  - service:
      name: snmpd
      state: stopped
      enabled: no
    when: snmpd_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.14


  - name: 2.2.8-14 Ensure DNS,FTP,HTTP,IMAP,POP,Samba,Proxy,SNMP Servers are not enabled (Not Scored)
    service: >
        name={{ item }}
        enabled=no
    with_items:
      - bind9
      - vsftpd
      - apache2
      - dovecot
      - smbd
      - squid3
      - snmpd
    failed_when: False
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.08
      - section02.02.09
      - section02.02.10
      - section02.02.11
      - section02.02.12
      - section02.02.13
      - section02.02.14


  - name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
    apt:
      name: postfix
      state: present
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.15

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^inet_interfaces'
      line: 'inet_interfaces = localhost'
      state: present
      create: no
    notify: restart postfix
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.15

  - name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
    stat: path=/etc/postfix/main.cf
    register: postfix_main_cf
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.15


  - name: 2.2.16 Ensure rsync service is not enabled (Scored)
    command: dpkg-query -s rsync
    register: rsync_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.16

  - service:
      name: rsync
      state: stopped
      enabled: no
    when: rsync_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.16

  - name: 2.2.16 Ensure rsync service is not enabled (Scored)
    stat: path=/etc/default/rsync
    register: default_rsync
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.16

  - lineinfile: >
        dest='/etc/default/rsync'
        regexp='^RSYNC_ENABLE'
        line='RSYNC_ENABLE=false'
    when: default_rsync.stat.exists == True
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.16


  - name: 2.2.17 Ensure NIS Server is not enabled (Scored)
    command: dpkg-query -s nis
    register: nis_installed
    failed_when: False
    ignore_errors: True
    changed_when: False
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.17

  - service:
      name: nis
      state: stopped
      enabled: no
    when: nis_installed.rc == 0
    tags:
      - not-for-trusty
      - level1
      - section02
      - section02.02
      - section02.02.17

  - name: 2.2.17 Ensure NIS Server is not enabled (Scored)
    apt: name=nis state=absent purge=yes
    tags:
      - not-for-xenial
      - level1
      - section02
      - section02.02
      - section02.02.17

