---

  - name: 4.3 Ensure logrotate is configured (Not Scored)
    file:
      name: "{{ item }}"
    with_items:
      - '/etc/logrotate.conf'
    tags:
      - level1
      - section04
      - section04.03
